### ISSUE TITLE
Unable to run seo.js Script -   Unexpected token import

### ISSUE THREAD

**Issue by gabrielecontitaguali** [DivanteLtd/vue-storefront-api#134]
Hi guys, 

i'm encountering a problem running seo script to generate redirects from old magento url structure to new vs.

This is the output from console

```
$ node scripts/seo.js
/home/www/malianta/vue-storefront-api/scripts/seo.js:1
(function (exports, require, module, __filename, __dirname) { import CommandRouter from 'command-router'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.
```
Does anyone faced the same issue?

**Comment by dimasch** [comment]
I have the same issue with `kue-dashboard` command
![2018-10-31_09-59-21](https://user-images.githubusercontent.com/414067/47809885-5acdcf80-dd5b-11e8-8fa6-19b616c69bce.png)

**Comment by qbo-tech** [comment]
Same here. The problem seems to be the presets argument for the "dev" script that used to be defined on package.json as `nodemon -w src --exec \"babel-node src --presets env,stage-0\"`. Before it was before as : `nodemon -w src --exec \"babel-node src --presets es2015,stage-0\"`. 

Without this parameter (--presets es2015), theres no way to use "import".

That change was made here:

https://github.com/DivanteLtd/vue-storefront-api/commit/9ee9209fbd5d1f4cc6e5ce1c6e0693bfa76cffa3#diff-be3c505e70d275070ea8b2bb36ce1b47

@DavidRouyer could you please tell us anything about it ?

**Comment by DavidRouyer** [comment]
Take a look at https://github.com/DivanteLtd/vue-storefront-api/pull/135
