### ISSUE TITLE
Many of us can't run docker

### ISSUE THREAD

**Issue by FreddyCrugger** [DivanteLtd/vue-storefront-api#308]
Hello,

Many of us cannot run docker, will you ever create a secondary way(official) to install Vue storefront?
Docker is not supported by many hosts + windows 10 home cannot run it.
Paying for a windows update and reinstall a big pc just to run docker won't be a fun process for most of us.

Thank you.

**Comment by EliotRaven** [comment]
ran into the problem that elasticsearch container crashed with error

**Comment by lukeromanowicz** [comment]
Please provide error log and steps for reproducing the issue.

**Comment by janmyszkier** [comment]
@lukeromanowicz [windows HOME doesn't support Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements) which is [required for docker to work](https://docs.docker.com/docker-for-windows/install/). 

What @FreddyCrugger said is not fixable by something we can do. An option would probably be to provide a VM (additionally to docker) with the setup  for all the people that do not want/cannot run docker setup. I also think it's going to be easier to debug VM when we compare it with docker.

Another point is that if you are buying a computer for WORK, you shouldn't be using Windows Home (but FFS everyone, do not open a discussion about windows here!), and we should probably not support Windows Home at all because of all the problems it brings to the table we shouldn't be providing workarouds for.

another option would be to take some cheap windows pro laptop (if possible) and start to build a debugging guide starting from the cheapest machine 

yet another option would be to dedicate someone on Slack to provide support for all those questions and build the docs based on the community questions. I don't think the current doc maintainer can do all the work, though.

**Comment by FreddyCrugger** [comment]
Hi janmyszkier,

Docker is also not supported by all web hosts at the moment, this is why it is a pain(on the top of the Windows problem).
It is ok I will stick to whatever works on Laragon, it is easier and I just love the technology.

Thank you.

**Comment by janmyszkier** [comment]
@FreddyCrugger in case of web hostings that do not support docker, you can follow
https://docs.vuestorefront.io/guide/installation/production-setup.html
